name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run golangci-lint
      uses: actions-contrib/golangci-lint@v1
      run: golangci-lint run .
    - name: Run tests and attempt building
      run: |
        export PATH=$(go env GOPATH)/bin:$PATH
        go test -v -race ./...
        go build
